// packages/frontend/src/components/campaign-creation-form/deploy/approve-rewards/ApproveRewards.vue
<script setup lang="ts">
import { useAccount, useReadContract, useReadContracts } from "vevm";
import { ref } from "vue";
import type { ApproveRewardsProps } from "./types";
import type { Reward } from "@/types";
import { computed } from "vue";
import { erc20Abi, type Address, parseUnits } from "viem";
import { watchEffect } from "vue";
import ApproveReward from "../approve-reward/ApproveReward.vue";
import { metromAbi } from "@metrom-xyz/contracts/abi";

const props = defineProps<ApproveRewardsProps>();
const emits = defineEmits(["allApproved"]);

const account = useAccount();

const rewardsToApprove = ref<Required<Reward[]>>(
    (props.rewards as Required<Reward[]>) || [],
);
const allRewardsApproved = ref(false);
const approvingRewardIndex = ref(0);

const approvingReward = computed(
    () =>
        rewardsToApprove.value[approvingRewardIndex.value] as Required<Reward>,
);

const { data: fee, loading: loadingGlobalFee } = useReadContract({
    address: props.metrom.address,
    abi: metromAbi,
    functionName: "fee",
});

const { data: allowances, loading: loadingAllowances } = useReadContracts(
    computed(() => ({
        contracts:
            (account.value.isConnected &&
                account.value.address &&
                props.rewards.map((reward) => {
                    return {
                        address: reward.token?.address as Address,
                        abi: erc20Abi,
                        functionName: "allowance",
                        args: [account.value.address, props.metrom.address],
                    };
                })) ||
            [],
    })),
);

function handleApproveRewardOnClick() {
    const updatedIndex = approvingRewardIndex.value + 1;
    if (!rewardsToApprove.value[updatedIndex]) {
        emits("allApproved");
        allRewardsApproved.value = true;
    } else approvingRewardIndex.value = updatedIndex;
}

watchEffect(() => {
    if (
        !allowances.value ||
        !props.rewards ||
        allowances.value.length !== props.rewards.length
    )
        return;

    const newToApprove = [];
    for (let i = 0; i < props.rewards.length; i++) {
        const reward = props.rewards[i] as Required<Reward>;
        if (
            allowances.value[i]?.result === null ||
            allowances.value[i]?.result === undefined ||
            !reward.amount
        )
            return;
        if (
            (allowances.value[i].result as bigint) >=
            parseUnits(reward.amount.toString(), reward.token.decimals)
        )
            continue;
        newToApprove.push(reward);
    }

    if (newToApprove.length === 0) {
        allRewardsApproved.value = true;
        return;
    }

    rewardsToApprove.value = newToApprove;
});
</script>
<template>
    <ApproveReward
        :metrom="$props.metrom"
        :fee="fee"
        :reward="approvingReward"
        :index="approvingRewardIndex"
        :total="rewardsToApprove.length"
        :loading="loadingAllowances || loadingGlobalFee"
        :disabled="$props.disabled"
        :onApprove="handleApproveRewardOnClick"
    />
</template>
<style></style>

// packages/frontend/src/components/create-campaign/approve-rewards-button/approve-rewards.tsx
import { useCallback, useState, useEffect } from "react";
import { useReadContracts, useAccount, useReadContract } from "wagmi";
import { type Address, erc20Abi, formatUnits } from "viem";
import type { CampaignPayload } from "@/src/types";
import { ApproveReward } from "./approve-reward";
import type { TokenAmount } from "@metrom-xyz/sdk";
import { metromAbi } from "@metrom-xyz/contracts/abi";
import { useChainData } from "@/src/hooks/useChainData";

interface ApproveRewardsProps {
    rewards?: CampaignPayload["rewards"];
    spender?: Address;
    disabled: boolean;
    onApprove: () => void;
}

export function ApproveRewards({
    rewards,
    spender,
    disabled,
    onApprove,
}: ApproveRewardsProps) {
    const chainData = useChainData();
    const { address: connectedAddress } = useAccount();

    const [currentIndex, setCurrentIndex] = useState(0);
    const [checkingApprovals, setCheckingApprovals] = useState(false);
    const [toApprove, setToApprove] = useState(rewards || []);
    const currentlyApprovingReward: TokenAmount | undefined =
        toApprove[currentIndex];

    const { data: fee, isLoading: loadingGlobalFee } = useReadContract({
        address: chainData.metromContract.address,
        abi: metromAbi,
        functionName: "fee",
    });

    const { data: allowances, isLoading: loadingAllowances } = useReadContracts(
        {
            contracts:
                connectedAddress &&
                spender &&
                rewards?.map((reward) => {
                    return {
                        address: reward.token.address,
                        abi: erc20Abi,
                        functionName: "allowance",
                        args: [connectedAddress, spender],
                    };
                }),
            query: {
                enabled: !!connectedAddress && !!rewards && !!spender,
            },
        },
    );

    useEffect(() => {
        if (!allowances || !rewards || allowances.length !== rewards.length)
            return;

        setCheckingApprovals(true);
        const newToApprove = [];
        for (let i = 0; i < rewards.length; i++) {
            const reward = rewards[i];
            if (
                allowances[i]?.result === null ||
                allowances[i]?.result === undefined
            )
                return;
            if (
                Number(
                    formatUnits(
                        allowances[i].result as bigint,
                        reward.token.decimals,
                    ),
                ) >= reward.amount
            )
                continue;
            newToApprove.push(reward);
        }
        if (newToApprove.length === 0) {
            onApprove();
            setCheckingApprovals(false);
            return;
        }
        setCheckingApprovals(false);
        setToApprove(newToApprove);
    }, [allowances, onApprove, rewards]);

    const handleApprove = useCallback(() => {
        if (!spender) {
            console.warn(
                "spender is undefined while handling approval: inconsistent state",
            );
            return;
        }

        const updatedIndex = currentIndex + 1;
        if (!toApprove[updatedIndex]) {
            onApprove();
        } else setCurrentIndex(updatedIndex);
    }, [currentIndex, onApprove, spender, toApprove]);

    return (
        <ApproveReward
            loading={
                checkingApprovals ||
                loadingAllowances ||
                loadingGlobalFee ||
                !currentlyApprovingReward ||
                !spender
            }
            disabled={disabled}
            fee={fee}
            reward={currentlyApprovingReward}
            index={currentIndex + 1}
            totalAmount={rewards?.length || 0}
            spender={spender}
            onApprove={handleApprove}
        />
    );
}
